on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "Dockerlog"
        run: docker login --username  ${{ secrets.DOCKER_USER }} --password ${{ secrets.DOCKER_PASS }}

      - name: "imageBuild"
        run: docker build -t ${{ secrets.DOCKER_USER }}/mustafa .

      - name: "Dockerpush"
        run: docker push ${{ secrets.DOCKER_USER }}/mustafa